# Generated by Django 3.2.8 on 2024-06-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerca_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Correo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254, verbose_name='correo_usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=1, max_length=30, verbose_name='nombre_usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
