# Generated by Django 3.2.8 on 2024-06-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerca_App', '0004_auto_20240617_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(default='Producto X', max_length=30, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos/', verbose_name='imagen'),
        ),
    ]
