# Generated by Django 3.2.8 on 2024-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerca_App', '0005_auto_20240622_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buzon',
            fields=[
                ('id_buzon', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=30, verbose_name='run')),
                ('apellido_paterno', models.CharField(max_length=30, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=30, verbose_name='apellido_materno')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('nombre_solicitud', models.CharField(max_length=30, verbose_name='nombre_solicitud')),
                ('correo_solicitud', models.EmailField(default='ejemplo@ejemplo.com', max_length=254, verbose_name='correo')),
                ('mensaje', models.CharField(max_length=300, verbose_name='mensaje')),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(default='Producto X', max_length=200, verbose_name='descripcion'),
        ),
    ]
