# Generated by Django 3.2.8 on 2024-07-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerca_App', '0006_auto_20240623_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='contrasenia_admin',
            field=models.CharField(default='', max_length=50, verbose_name='contrasenia_admin'),
        ),
    ]
